=pod

=head1 NAME

FLTK::ccCellBox - Part of the FLTK::ColorChooser megawidget

=head1 Description



=head1 Functions

=head2 C<new>
X<new>

=over

=item C<my $cb = $cccellbox-E<gt>new( $x, $y, $w, $h );>X<my_cb_cccellbox_E_gt_new_x_y_w_h_>



=pod 

=for hackers xs/ccCellBox.xs line 29

=back

=head1 Author

Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

=head1 License and Legal

Copyright (C) 2008-2010 by Sanko Robinson <sanko@cpan.org>

This program is free software; you can redistribute it and/or modify it under
the terms of
L<The Artistic License 2.0|http://www.perlfoundation.org/artistic_license_2_0>.
See the F<LICENSE> file included with this distribution or
L<notes on the Artistic License 2.0|http://www.perlfoundation.org/artistic_2_0_notes>
for clarification.

When separated from the distribution, all original POD documentation is
covered by the
L<Creative Commons Attribution-Share Alike 3.0 License|http://creativecommons.org/licenses/by-sa/3.0/us/legalcode>.
See the
L<clarification of the CCA-SA3.0|http://creativecommons.org/licenses/by-sa/3.0/us/>.


=for git $Id: ccCellBox.xs 7483df2 2011-04-09 05:42:22Z sanko@cpan.org $

=cut
