=pod

=head1 NAME

FLTK::HighlightButton - This button highlights even if the default style does not do so

=head1 Description

Same as a normal button but the L<C<box()>|/"box"> defaults to a style that
draws as a flat rectangle until the mouse points at it, then it draws as a
raised highlighted rectangle.

=head1 Functions

=head2 C<new>
X<new>

=over

=item C<my $button = $highlightbutton-E<gt>new( $x, $y, $w, $h, $label );>X<my_button_highlightbutton_E_gt_new_x_y_w_h_label_>

Creates a new C<FLTK::HighlightButton> object. Obviously.

=pod 

=for hackers xs/HighlightButton.xs line 33

=back

=head1 Author

Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

=head1 License and Legal

Copyright (C) 2008-2010 by Sanko Robinson <sanko@cpan.org>

This program is free software; you can redistribute it and/or modify it under
the terms of
L<The Artistic License 2.0|http://www.perlfoundation.org/artistic_license_2_0>.
See the F<LICENSE> file included with this distribution or
L<notes on the Artistic License 2.0|http://www.perlfoundation.org/artistic_2_0_notes>
for clarification.

When separated from the distribution, all original POD documentation is
covered by the
L<Creative Commons Attribution-Share Alike 3.0 License|http://creativecommons.org/licenses/by-sa/3.0/us/legalcode>.
See the
L<clarification of the CCA-SA3.0|http://creativecommons.org/licenses/by-sa/3.0/us/>.


=for git $Id: HighlightButton.xs c629eeb 2010-09-27 04:12:30Z sanko@cpan.org $

=cut
