=pod

=head1 NAME

FLTK::RadioItem - This widget makes a radio item in a popup or pulldown Menu

=head1 Description

This widget makes a radio item in a popup or pulldown L<Menu|FLTK::Menu>. Its
behavior in a L<Browser|FLTK::Browser> or L<MultiBrowser|FLTK::MultiBrowser>
is that it changes its status on multiple clicks (e.g. double click).

=head1 Functions

=head2 C<new>
X<new>

=over

=item C<my $self = $radioitem-E<gt>new( $label );>X<my_self_radioitem_E_gt_new_label_>

Unlike other widgets the constructor does not take any dimensions, since it is
assummed the container widget will size this correctly.

=for hackers xs/RadioItem.xs line 33

=item C<my $self = $radioitem-E<gt>new( $label, $shortcut, \&callback, $user_data, $flags );>X<my_self_radioitem_E_gt_new_label_shortcut_callback_user_data_flags_>

This constructor is provided to match the L<C<Menu::add()>|FLTK::Menu/"add">
function arguments. See L<C<Menu::add()>|FLTK::Menu/"add"> for more details.

=pod 

=for hackers xs/RadioItem.xs line 38

=back

=head1 Author

Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

=head1 License and Legal

Copyright (C) 2008-2010 by Sanko Robinson <sanko@cpan.org>

This program is free software; you can redistribute it and/or modify it under
the terms of
L<The Artistic License 2.0|http://www.perlfoundation.org/artistic_license_2_0>.
See the F<LICENSE> file included with this distribution or
L<notes on the Artistic License 2.0|http://www.perlfoundation.org/artistic_2_0_notes>
for clarification.

When separated from the distribution, all original POD documentation is
covered by the
L<Creative Commons Attribution-Share Alike 3.0 License|http://creativecommons.org/licenses/by-sa/3.0/us/legalcode>.
See the
L<clarification of the CCA-SA3.0|http://creativecommons.org/licenses/by-sa/3.0/us/>.


=for git $Id: RadioItem.xs c629eeb 2010-09-27 04:12:30Z sanko@cpan.org $

=cut
